embedding_size: 64
feat_embed_dim: 64
weight_size:
- 64
- 64
lambda_coeff: 0.9
reg_weight: 1e-05
hyper_parameters:
- rf_inference_mix_ratio
n_mm_layers: 1
n_ui_layers: 2
knn_k: 10
mm_image_weight: 0.1
dropout: 0.8
use_rf: true
rf_hidden_dim: 128
rf_n_layers: 2
rf_dropout: 0.1
rf_sampling_steps: 5
rf_learning_rate: 0.0001
rf_loss_weight: 0.6
rf_warmup_epochs: 20
rf_mix_ratio: 0
rf_inference_mix_ratio:
- 0.02
- 0.05
- 0.1
rf_contrast_temp: 0.1
use_denoise: true
clean_rating_threshold: 5.0
denoise_layers: 2
ps_loss_weight: 0.1
use_2rf: false
use_wandb: true
wandb_project: GenMMRec_RFFREEDOM_SEARCH
